//
// Autogenerated by Thrift Compiler (0.8.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;
var ttypes = module.exports = {};
var Member = module.exports.Member = function(args) {
  this.id = null;
  this.first = null;
  this.last = null;
  this.rank = null;
  if (args) {
    if (args.id !== undefined) {
      this.id = args.id;
    }
    if (args.first !== undefined) {
      this.first = args.first;
    }
    if (args.last !== undefined) {
      this.last = args.last;
    }
    if (args.rank !== undefined) {
      this.rank = args.rank;
    }
  }
};
Member.prototype = {};
Member.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.id = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.first = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.last = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.rank = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Member.prototype.write = function(output) {
  output.writeStructBegin('Member');
  if (this.id) {
    output.writeFieldBegin('id', Thrift.Type.I32, 1);
    output.writeI32(this.id);
    output.writeFieldEnd();
  }
  if (this.first) {
    output.writeFieldBegin('first', Thrift.Type.STRING, 2);
    output.writeString(this.first);
    output.writeFieldEnd();
  }
  if (this.last) {
    output.writeFieldBegin('last', Thrift.Type.STRING, 3);
    output.writeString(this.last);
    output.writeFieldEnd();
  }
  if (this.rank) {
    output.writeFieldBegin('rank', Thrift.Type.I32, 4);
    output.writeI32(this.rank);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

